---
title: "NRCS Wisconsin Sites Map"
output: html_notebook
note: "Jade Kochanski's R code modified from Jeremy Hemberger's originial"
editor_options: 
  chunk_output_type: inline
---

# Load packages
```{r}
library(ggplot2)
library(ggmap)
library(maps)
library(mapdata)
library(tidyverse)
library(grid)
library(ggsn)
library(ggspatial)
```

# practice plot with USA
```{r}
usa <- map_data("usa") #load in the data for the map
gg1 <- ggplot() + geom_polygon(data = usa, aes(x=long, y = lat, group = group), fill = "grey", color = "black") + coord_fixed(1.3) #plot the map

#load in df with site coordinates and categories
sites <- read.csv("../raw/site_history.csv")
```


```{r}
#plot the USA map with your site points on it
gg1 + 
  geom_point(data = sites, aes(x = x.lon, y = y.lat), color = "black", size = 1) + theme_bw() 
```
# States
## light grey version
```{r}
states <- map_data("state") #load data for each state

wi <- subset(states, region =="wisconsin") #create object with wi data

#plot the states
ggplot(data = states) + 
  geom_polygon(aes(x = long, y = lat, fill = region, group = group), fill = "#cccccc", color = "white") + 
  coord_fixed(1.3) +
  guides(fill=FALSE) + # do this to leave off the color legend
  geom_polygon(data = wi, aes(x = long, y = lat),fill = "#f7f7f7", color = "black")+ #this line won't work unless you run the next chunk first to get the wi object.
  geom_point(data = sites, aes(x = x.lon, y = y.lat), color = "#43a2ca", size = 2) + 
  theme_nothing() 

#ggsave("../figures/usa_sites.jpeg")
```

## colored version
```{r}
#plot the states
ggplot(data = states) + 
  geom_polygon(aes(x = long, y = lat, fill = region, group = group), fill = "white", color = "black") + 
  coord_fixed(1.3) +
  theme(panel.background = element_rect(fill = "transparent",
                                  colour = NA_character_)) + 
  guides(fill=FALSE) + # do this to leave off the color legend
  geom_polygon(data = wi, aes(x = long, y = lat),fill = "#D58936", color = "black")+ #this line won't work unless you run the next chunk first to get the wi object.
  theme_nothing() 

#ggsave("../figures/usa_wi.jpeg")
```


# Wisconsin
```{r}
#map of wisconsin
ggplot(data = wi) + 
  geom_polygon(aes(x = long, y = lat, group = group), fill = "#f0f0f0", color = "black") + 
  coord_fixed(1.3) + scalebar(wi, dist = 50, st.size=3, height=0.025, dist_unit = "km",
             transform = TRUE, model = "WGS84", location = "bottomleft") +
  theme_nothing()

#create dfs for county lines
counties <- map_data("county")
wi_county <- subset(counties, region == "wisconsin")
head(wi_county)
```


# Wisconsin with plain points
```{r}
wi_b <- ggplot(data = wi, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(color = "black", fill = "#f0f0f0") #can change background color of map

wi_b #view map

wi_m <- wi_b + theme_nothing()+ #theme_nothing gets rid of grid lines 
  geom_polygon(data = wi_county, fill = NA, color = "white") + #this makes white outline of county
  geom_polygon(color = "black", fill = NA) + 
  geom_point(data = sites, color = "black", mapping = aes(x = x.lon, y = y.lat),
             color = "black", size = 0.5, inherit.aes = FALSE)#add points for your sites

wi_m 

#uncomment to save and export your map
#ggsave("./Figures/wisconsin.plain.pdf")
#ggsave("../figures/wi_m.png")
```

# Wisconsin with points as Year
```{r}
wi_base <- ggplot(data = wi, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(color = "black", fill = "#f0f0f0")

wi_base

color <- factor(sites$VisitYear, levels = c("2021", "2022", "Both"))

wi_map <- wi_base + theme_nothing() +
  geom_polygon(data = wi_county, fill = NA, color = "#d9d9d9") +
  geom_polygon(color = "black", fill = NA) + 
  geom_point(data = sites, mapping = 
               aes(x = x.lon, y = y.lat, shape=color, color = color), 
             size = 3, inherit.aes = FALSE) +
  scale_color_manual(values = c("#252525", "#969696", "#252525")) + 
  scale_shape_manual(values = c(1,19,19)) #+
  #scale_shape_manual(values = c(16,16,17)) +
 # scalebar(wi, dist = 50, st.size=3, height=0.025, dist_unit = "km",
 #            transform = TRUE, model = "WGS84", location = "bottomleft")

wi_map

#ggsave("../figures/sites.jpeg")

```

# Close up of sites
```{r}
close_up <- wi_map + coord_fixed(xlim = c(-89.6, -88.2),  ylim = c(42.5, 43.65), ratio = 1.3) 

close_up
```


# Close up of sites
```{r}
southern_wi <- wi %>%
  filter(long <= -88.2 & long >= -89.6) %>%
  filter(lat >= 42.5 & lat <= 43.65)

#c(-89.6, -88.2),  ylim = c(42.5, 43.65),

#southern_county <- wi_county %>%
#  filter(long <= -87.67 & long >= -90) %>%
#  filter(lat >= 42.49 & lat <= 44.25)

southern_county <- wi_county %>%
  filter(long <= -87.67 & long >= -89.6) %>%
  filter(lat >= 42.49 & lat <= 43.5)

wi_b <- ggplot(data = southern_county, mapping = aes(x = long, y = lat, group = group)) + 
  coord_fixed(1.3) + 
  geom_polygon(color = "black", fill = "#f0f0f0")

wi_b

wi_b + theme_nothing() +
  geom_polygon(data = southern_county, fill = NA, color = "white") +
  geom_polygon(color = "white", fill = "#f0f0f0") + 
  geom_point(data = sites, mapping = 
               aes(x = x.lon, y = y.lat, shape = color, color = color), 
             size = 4, inherit.aes = FALSE) +
  scale_color_manual(values = c("#252525", "#969696", "#252525")) + 
  scale_shape_manual(values = c(1,19,19)) +
 # scalebar(southern_wi, dist = 50, st.size=5, height=0.025, dist_unit = "km",
  #           transform = TRUE, model = "WGS84", location = "bottomright") +
  coord_sf()


wi_map + theme_nothing() +
  coord_sf(xlim=c(-89.6, -88.2),  ylim = c(42.6, 43.7), expand = F)# +
  ggsn::scalebar(southern_county, dist = 50, st.size=5, height=0.025, dist_unit = "km",
             transform = TRUE, model = "WGS84", location = "bottomright",
             x.min = 42.5, x.max = 43.9, y.max = -89.2, y.min = -88.1)

wi_map + theme_nothing() +
  coord_sf(xlim=c(-89.6, -88.2),  ylim = c(42.6, 43.7), expand = F) +
  ggspatial::annotation_scale(location="tl", plot_unit = "km")

#ggsave("../figures/sites_zoomed.jpeg")
```

